version: '3'
services:
  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '13306:3306'
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: app:lastest
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./docker-entrypoint.dev.sh
    environment:
      DB_HOST: db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - .:/rails
    ports:
      - "3100:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db_data:  